version: '3.3'

services:
  web:
    container_name: nginx
    hostname: nginx-box
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
        - php
    working_dir: /var/www
    volumes:
      - ../app:/var/www:delegated
      - ./logs/nginx:/var/log/nginx
      - ./image/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
      - cc-test-app-net

  php:
    container_name: php_fpm
    hostname: php-fpm-box
    image: ${NAME_PREFIX}
    env_file:
      - ./.env
    environment:
      PHP_IDE_CONFIG: serverName=${SERVER_NAME}
      XDEBUG_IDEKEY: ${XDEBUG_IDEKEY}
    volumes:
      - ../app/:/var/www:delegated
    networks:
      - default
      - cc-test-app-net

networks:
  default:
    driver: bridge
  cc-test-app-net:
    external: true # if not created manually run command `docker network create cc-test-app-net`
